# ~1.0B dense decoder (20L x 2048d, 32 heads)
vocab_size: 32000
n_layer: 20
n_head: 32
n_kv_head: 8
n_embd: 2048
seq_len: 4096

dropout: 0.0
rope_base: 10000.0
rope_scale: 1.5
rope_mode: "yarn"
qk_norm: false
tie_weights: true
checkpoint: true

batch_size: 2
grad_accum: 32
lr: 3e-4
min_lr: 3e-5
warmup_steps: 2000
weight_decay: 0.1
grad_clip: 1.0
z_loss: 1e-4

amp: true
bf16: true
compile: false
