# ~0.5B dense decoder (16L x 1536d, 24 heads)
vocab_size: 32000
n_layer: 16
n_head: 24
n_kv_head: 8
n_embd: 1536
seq_len: 4096

dropout: 0.0
rope_base: 10000.0
rope_scale: 1.5
rope_mode: "yarn"   # supported: ntk|yarn (scales RoPE angles)
qk_norm: false
tie_weights: true
checkpoint: true

# training
batch_size: 1
grad_accum: 32
lr: 3e-4
min_lr: 3e-5
warmup_steps: 2000
weight_decay: 0.1
grad_clip: 1.0
z_loss: 1e-4

amp: true
bf16: true
compile: false
